### ISSUE TITLE
Continuous integration with Travis-CI

### ISSUE THREAD

**Issue by steve-lebleu** [steve-lebleu/kompleter#6]
Testing not working by travis

**Comment by e-lLess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Completer.js](https://trello.com/c/5ysgCbdh/1-completer-js)

**Comment by e-lLess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix testing procedure](https://trello.com/c/5ysgCbdh/1-fix-testing-procedure)

**Comment by e-lLess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixer procédure de test](https://trello.com/c/8TZuLZk3/1-fixer-proc%C3%A9dure-de-test)

**Comment by steve-lebleu** [comment]
Finally done with Github actions.
