### ISSUE TITLE
Tests e2e with Cypress

### ISSUE THREAD

**Issue by steve-lebleu** [steve-lebleu/kompleter#7]
Write more tests

**Comment by e-lLess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write tests](https://trello.com/c/bsDqkne4/2-write-tests)

**Comment by e-lLess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rédiger tests](https://trello.com/c/L6WUiahF/2-r%C3%A9diger-tests)

**Comment by steve-lebleu** [comment]
Done.
